# Generated by Django 2.0.4 on 2018-05-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='location',
        ),
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.CharField(default='Stony Brook', max_length=30),
        ),
        migrations.AddField(
            model_name='attraction',
            name='region',
            field=models.CharField(default='NY', max_length=2),
        ),
    ]
