# Generated by Django 2.0.4 on 2018-05-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='companyName',
            field=models.CharField(default='hotel', max_length=30),
        ),
    ]
