# Generated by Django 2.0.4 on 2018-05-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellite', '0004_auto_20180507_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('author', models.CharField(max_length=30)),
                ('submissionDate', models.DateField()),
            ],
        ),
    ]
